force-app/main/default/objects/Grupo__c/Grupo__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <displayFormat>GRP-{0000}</displayFormat>
        <label>Grupo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grupo__c/fields/Permissoes__c.field-meta.xml
<CustomField>
    <fullName>Permissoes__c</fullName>
    <inlineHelpText>Insira os valores separados por vírgula, sem espaços extras. Cada valor deve começar com letra maiúscula. Exemplo: Admin,Read,Write,Delete</inlineHelpText>
    <label>Permissões</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GrupoActions.cls
public with sharing class GrupoActions {

    public static void formatsPermissions(List<Grupo__c> newGroups) {
        for (Grupo__c gp : newGroups) {
            if (String.isNotBlank(gp.Permissoes__c)) {
                List<String> permissions = gp.Permissoes__c.split(',');
                for (Integer i = 0; i < permissions.size(); i++) {
                    permissions[i] = permissions[i].trim().capitalize();
                }
                gp.Permissoes__c = String.join(permissions, ',');
            }
        }
    }
}