force-app/main/default/objects/Grupo__c/Grupo__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <displayFormat>GRP-{0000}</displayFormat>
        <label>Grupo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grupo__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grupo__c/fields/Permissoes__c.field-meta.xml
<CustomField>
    <fullName>Permissoes__c</fullName>
    <inlineHelpText>Insira os valores separados por vírgula, sem espaços extras. Cada valor deve começar com letra maiúscula. Exemplo: Admin,Read,Write,Delete</inlineHelpText>
    <label>Permissões</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UsuarioGrupo__c/UsuarioGrupo__c.object-meta.xml
<CustomObject>
    <label>Usuário grupo</label>
    <nameField>
        <displayFormat>USG-{0000}</displayFormat>
        <label>Usuário grupo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuários grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UsuarioGrupo__c/fields/GrupoId__c.field-meta.xml
<CustomField>
    <fullName>GrupoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo id</label>
    <referenceTo>Grupo__c</referenceTo>
    <relationshipLabel>Usuários grupos</relationshipLabel>
    <relationshipName>Usuarios_grupos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserPermissionService.cls
public with sharing class UserPermissionService {

    public static Map<String, List<String>> returnPermissions( Id userId ) {
        List<UsuarioGrupo__c> userGroup = UsuarioGrupoRepository.getByUserId(userId);

        List<Id> idsGroup = new List<Id>();
        for(UsuarioGrupo__c groupId : userGroup) {
            idsGroup.add(groupId.GrupoId__c);
        }

        List<Grupo__c> groups = GroupRepository.getById(idsGroup);

        Map<String, List<String>> mapGroups = splitPermissions(groups);

        return mapGroups;
    }

    private static Map<String, List<String>> splitPermissions( List<Grupo__c> groups ) {
        Map<String, List<String>> mapGroups = new Map<String, List<String>>();
        for(Grupo__c gp : groups) {
            if(!String.isBlank(gp.Permissoes__c)){
                Set<String> uniquePermissions = new Set<String>(gp.Permissoes__c.split(','));
                mapGroups.put(gp.Nome__c, new List<String>(uniquePermissions));
            } else {
                mapGroups.put(gp.Nome__c, new List<String>());
            }
        }
        return mapGroups;
    }
}